=== encarbassotnopot/proven_m04/uf1/nf2/pe2/Exercici1/institut.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Institut -->
<!ELEMENT institut (anys)>
<!ATTLIST institut nom CDATA #REQUIRED>

<!ELEMENT anys (any*)>

<!ELEMENT any (cicle+)>
<!ATTLIST any curs CDATA #REQUIRED>

<!ELEMENT cicle (alumne+)>
<!ATTLIST cicle nom (DAM | DAW | DAWBio | ASIX) #REQUIRED>

<!-- Alumne -->
<!ELEMENT alumne (dades, expedient)>
<!ATTLIST alumne matrícula ID #REQUIRED>

<!-- Alumne Dades -->
<!ELEMENT dades (dni, nom, cognom, estudis, telèfon, email?)>

<!ELEMENT dni (#PCDATA)>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT cognom (#PCDATA)>

<!ELEMENT estudis (estudi*)>

<!ELEMENT estudi (#PCDATA)>
<!ATTLIST estudi anyFinal CDATA #IMPLIED>

<!ELEMENT telèfon (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!-- Alumne Expedient -->
<!ELEMENT expedient (mòdul+)>

<!ELEMENT mòdul (#PCDATA)>
<!ATTLIST mòdul codi CDATA #REQUIRED>
<!ATTLIST mòdul nom CDATA #REQUIRED>
<!ATTLIST mòdul professor CDATA #REQUIRED>
<!ATTLIST mòdul aprovat CDATA #FIXED "aprovat">

=== encarbassotnopot/proven_m04/uf1/nf2/pe2/Exercici1/institut.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE institut SYSTEM "institut.dtd">
<institut nom="Provençana">
	<anys>
		<any curs="2022-2023">
			<cicle nom="DAM">
				<alumne matrícula="DAM-1238">
					<dades>
						<dni>12345678A</dni>
						<nom>Laia</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">CFGM Sistmes microinformàtics i xarxes</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
				<alumne matrícula="DAM-1239">
					<dades>
						<dni>12345679B</dni>
						<nom>Ona</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">Batxillerat</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
						<email> ona.hc@mail.com </email>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
			</cicle>
			<cicle nom="DAW">
				<alumne matrícula="DAW-6804">
					<dades>
						<dni>12345678A</dni>
						<nom>Laia</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">CFGM Sistmes microinformàtics i xarxes</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
				<alumne matrícula="DAW-35463">
					<dades>
						<dni>12345679B</dni>
						<nom>Ona</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">Batxillerat</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
						<email> ona.hc@mail.com </email>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
			</cicle>
			<cicle nom="DAWBio">
				<alumne matrícula="DAWBio-3849">
					<dades>
						<dni>12345678A</dni>
						<nom>Laia</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">CFGM Sistmes microinformàtics i xarxes</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
				<alumne matrícula="DAWBio-3584">
					<dades>
						<dni>12345679B</dni>
						<nom>Ona</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2020">ESO</estudi>
							<estudi anyFinal="2022">Batxillerat</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
						<email> ona.hc@mail.com </email>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
			</cicle>
			<cicle nom="ASIX">
				<alumne matrícula="ASIX-4514">
					<dades>
						<dni>12345678A</dni>
						<nom>Laia</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2022">ESO</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
				<alumne matrícula="ASIX-5431">
					<dades>
						<dni>12345679B</dni>
						<nom>Ona</nom>
						<cognom>Hernandez Camps</cognom>
						<estudis>
							<estudi anyFinal="2022">ESO</estudi>
						</estudis>
						<telèfon>632515032</telèfon>
						<email> ona.hc@mail.com </email>
					</dades>
					<expedient>
						<mòdul codi="M01" nom="Sistemes Informàtics" professor="Laura">4</mòdul>
						<mòdul codi="M02" nom="Bases de dades" professor="Èlia" aprovat="aprovat">10</mòdul>
						<mòdul codi="M03" nom="Programació" professor="Elenea" aprovat="aprovat">7</mòdul>
					</expedient>
				</alumne>
			</cicle>
		</any>
	</anys>
</institut>
